# Allgemeine Konfiguration
random_seed: 42
experiment_name: default_experiment

# Daten
data:
  # Für Tabular/Unsupervised
  input_csv: "data/raw/sample.csv"
  target_column: "target"
  datetime_column: "ds"   # für Time Series
  id_column: null

# Cross-Validation
cv:
  n_splits: 5
  shuffle: true

# Time Series
timeseries:
  frequency: null   # z.B. 'D', 'W', 'M' – falls du Resampling willst
  lags: [1, 7, 30]
  rolling_windows: [7, 30]
  add_fourier: true
  fourier_periods: [7, 30]
  seasonal_decompose: false  # benötigt ausreichende Länge

# Tuning
tuning:
  strategy: "random"   # "grid" oder "random"
  n_iter: 20
  n_jobs: -1
